version: '3'
 
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TestDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql #Dat info kde to bude

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  flaskserver:
    build:
      context: ./Api
      dockerfile: ./Dockerfile
    container_name: flaskserver
    ports:
      - 5000:5000
    volumes:
      - C:\Users\krajc\OneDrive - České vysoké učení technické v Praze\1. ČVUT- FBMI\1. ČVUT- FBMI\Vyuka\TBA\TBAnew\CV04\Api\app\configs:/app/configs
    links:
     - mysql


volumes:
  dbdata: